// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_option from "rescript/lib/es6/caml_option.js";

console.log([11]);

var app = document.querySelector("#app");

if (app !== undefined) {
  console.log(Caml_option.valFromOption(app));
} else {
  console.log("none");
}

export {
  
}
/*  Not a pure module */
